<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f9f9f9;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background: #fff;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        h1 {
            font-size: 24px;
            color: #444;
        }
        p {
            margin: 10px 0;
        }
        .message-box {
            background-color: #f1f1f1;
            border-left: 4px solid #FFD100;
            padding: 15px;
            margin: 20px 0;
            font-style: italic;
            color: #555;
        }
        .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <h1>New Customer Inquiry</h1>
        <p><strong>From:</strong> {{ $data['first_name'] }} {{ $data['last_name'] }}</p>
        <p><strong>Email:</strong> {{ $data['email'] }}</p>
        <p><strong>Message:</strong></p>
        <div class="message-box">
            {{ $data['message'] }}
        </div>
        <p>Please respond to this customer as soon as possible.</p>
        <div class="footer">
            <p>This email was automatically generated by {{ config('app.name') }}.</p>
        </div>
    </div>
</body>
</html>
